import React, { useState } from 'react';
import { X, Copy, Check, Database, Code, Cpu, Layers } from 'lucide-react';

interface SupabaseGuideModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SupabaseGuideModal: React.FC<SupabaseGuideModalProps> = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState<'sql' | 'esp32' | 'service'>('sql');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const sqlSchema = `-- 1. Create the weight_data table in Supabase SQL Editor
create table public.weight_data (
  id bigint generated by default as identity primary key,
  table_id text not null default 'TABLE-01',
  weight double precision not null,
  timestamp timestamptz not null default now()
);

-- 2. Enable Row Level Security (RLS) and allow public reads
alter table public.weight_data enable row level security;

create policy "Allow anonymous select"
on public.weight_data for select
to anon
using (true);

create policy "Allow ESP32 insert with API key"
on public.weight_data for insert
to anon
with check (true);

-- 3. Enable Realtime broadcasting
alter publication supabase_realtime add table public.weight_data;`;

  const esp32Code = `// ESP32 Arduino / PlatformIO C++ Snippet
#include <WiFi.h>
#include <HTTPClient.h>
#include "HX711.h"

const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";
const char* supabase_url = "https://your-project.supabase.co/rest/v1/weight_data";
const char* supabase_anon_key = "YOUR_SUPABASE_ANON_KEY";

HX711 scale;
const int LOADCELL_DOUT_PIN = 16;
const int LOADCELL_SCK_PIN = 4;
const float CALIBRATION_FACTOR = 420.5;

void setup() {
  Serial.begin(115200);
  scale.begin(LOADCELL_DOUT_PIN, LOADCELL_SCK_PIN);
  scale.set_scale(CALIBRATION_FACTOR);
  scale.tare(); // Zero out table tare weight

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
}

void loop() {
  if (WiFi.status() == WL_CONNECTED) {
    float weight = scale.get_units(5); // Average 5 readings in kg
    
    HTTPClient http;
    http.begin(supabase_url);
    http.addHeader("Content-Type", "application/json");
    http.addHeader("apikey", supabase_anon_key);
    http.addHeader("Authorization", String("Bearer ") + supabase_anon_key);
    http.addHeader("Prefer", "return=minimal");

    String payload = "{\\"table_id\\":\\"TABLE-01\\",\\"weight\\":" + String(weight, 1) + "}";
    int httpResponseCode = http.POST(payload);
    http.end();
  }
  delay(1000); // Sample every 1s
}`;

  const serviceCode = `// src/services/weightService.ts (Connecting to Supabase)
import { createClient } from '@supabase/supabase-js';
import { WeightRecord } from '../types/weight';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
export const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// 1. Fetch Latest Record:
export async function fetchCurrentWeight(tableId = 'TABLE-01'): Promise<WeightRecord> {
  const { data, error } = await supabase
    .from('weight_data')
    .select('*')
    .eq('table_id', tableId)
    .order('timestamp', { ascending: false })
    .limit(1)
    .single();
  if (error) throw error;
  return data;
}

// 2. Realtime WebSocket Subscription:
export function subscribeToWeightUpdates(callback: (record: WeightRecord) => void) {
  const channel = supabase
    .channel('realtime:weight_data')
    .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'weight_data' },
      payload => callback(payload.new as WeightRecord)
    )
    .subscribe();

  return () => { supabase.removeChannel(channel); };
}`;

  return (
    <div
      id="modal-supabase-guide"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs"
    >
      <div className="bg-slate-900 border border-slate-800 text-slate-100 rounded-xl w-full max-w-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <Database className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">
                Supabase Integration Blueprint
              </h2>
              <p className="text-xs text-slate-400">
                SQL schema, ESP32 firmware snippet, and frontend connector guide
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selector */}
        <div className="flex items-center gap-2 px-6 pt-4 border-b border-slate-800 bg-slate-950/40 text-xs">
          <button
            onClick={() => setActiveTab('sql')}
            className={`pb-3 px-3 font-semibold flex items-center gap-1.5 border-b-2 transition-colors ${
              activeTab === 'sql'
                ? 'border-emerald-500 text-emerald-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Database className="w-3.5 h-3.5" />
            <span>1. Supabase SQL Schema</span>
          </button>
          <button
            onClick={() => setActiveTab('esp32')}
            className={`pb-3 px-3 font-semibold flex items-center gap-1.5 border-b-2 transition-colors ${
              activeTab === 'esp32'
                ? 'border-emerald-500 text-emerald-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Cpu className="w-3.5 h-3.5" />
            <span>2. ESP32 Arduino C++ Code</span>
          </button>
          <button
            onClick={() => setActiveTab('service')}
            className={`pb-3 px-3 font-semibold flex items-center gap-1.5 border-b-2 transition-colors ${
              activeTab === 'service'
                ? 'border-emerald-500 text-emerald-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Code className="w-3.5 h-3.5" />
            <span>3. weightService.ts Client</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto font-mono text-xs">
          {activeTab === 'sql' && (
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-slate-400 font-sans font-medium">
                  Run this SQL in the Supabase Dashboard SQL Editor:
                </span>
                <button
                  onClick={() => handleCopy(sqlSchema, 'sql')}
                  className="flex items-center gap-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
                >
                  {copiedKey === 'sql' ? (
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                  <span>{copiedKey === 'sql' ? 'Copied' : 'Copy SQL'}</span>
                </button>
              </div>
              <pre className="p-4 rounded-lg bg-slate-950 border border-slate-800 text-emerald-300/90 overflow-x-auto whitespace-pre">
                {sqlSchema}
              </pre>
            </div>
          )}

          {activeTab === 'esp32' && (
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-slate-400 font-sans font-medium">
                  Flash this sketch to your ESP32 board using Arduino IDE / PlatformIO:
                </span>
                <button
                  onClick={() => handleCopy(esp32Code, 'esp32')}
                  className="flex items-center gap-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
                >
                  {copiedKey === 'esp32' ? (
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                  <span>{copiedKey === 'esp32' ? 'Copied' : 'Copy C++ Code'}</span>
                </button>
              </div>
              <pre className="p-4 rounded-lg bg-slate-950 border border-slate-800 text-indigo-300 overflow-x-auto whitespace-pre">
                {esp32Code}
              </pre>
            </div>
          )}

          {activeTab === 'service' && (
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-slate-400 font-sans font-medium">
                  Replace the mock methods in <code className="text-white">src/services/weightService.ts</code>:
                </span>
                <button
                  onClick={() => handleCopy(serviceCode, 'service')}
                  className="flex items-center gap-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
                >
                  {copiedKey === 'service' ? (
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                  <span>{copiedKey === 'service' ? 'Copied' : 'Copy Service Code'}</span>
                </button>
              </div>
              <pre className="p-4 rounded-lg bg-slate-950 border border-slate-800 text-slate-300 overflow-x-auto whitespace-pre">
                {serviceCode}
              </pre>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-950/60 flex items-center justify-between text-xs text-slate-400">
          <span>Current project is pre-structured for this exact contract.</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-md font-sans font-medium bg-emerald-600 hover:bg-emerald-500 text-white transition-colors"
          >
            Close Guide
          </button>
        </div>
      </div>
    </div>
  );
};
